language: go
go: 1.3

services:
  - mongodb # 2.4.12

install:
  - export PATH=$PATH:$HOME/gopath/bin
  - go get -v github.com/leanote/leanote/app

  # - go get github.com/revel/cmd/revel
  # - go install github.com/revel/cmd/revel
  - pwd
  - ls

script:
  - mongo --version
  - mongorestore -h localhost -d leanote --directoryperdb ./mongodb_backup/leanote_install_data/

  - go test github.com/leanote/leanote/app/tests

  # gen tmp/main.go, routes/routes.go
  - go run app/cmd/main.go
  # build
  - go build -o leanote github.com/leanote/leanote/app/tmp
  # run with port 9000
  - ./leanote -importPath=github.com/leanote/leanote -runMode=dev -port=9000 &
  # test
  - wget http://localhost:9000
  - wget http://localhost:9000/blog
  - wget http://localhost:9000/login
  - wget http://localhost:9000/demo

  # - revel build github.com/leanote/leanote tmp
  # OK